# Generated by Django 4.1 on 2024-08-11 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mytask", "0002_assignment_alter_task_options_task_assignees_and_more"),
    ]

    operations = []
