# Generated by Django 4.1 on 2024-08-24 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mytask.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mytask", "0003_auto_20240812_0046"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
            },
        ),
        migrations.RemoveField(
            model_name="task",
            name="assignees",
        ),
        migrations.AddField(
            model_name="task",
            name="handler",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="handled_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("REVIEWING", "审核中"),
                    ("REJECTED", "已退回"),
                    ("ASSIGNED", "已派发"),
                    ("FORWARDED", "已转发"),
                    ("COMPLETED", "已完成"),
                ],
                default="REVIEWING",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.CharField(
                default=mytask.models.generate_unique_task_id,
                max_length=10,
                unique=True,
            ),
        ),
    ]
