# Generated by Django 4.1 on 2024-09-21 15:14

from django.db import migrations, models
import mytask.models


class Migration(migrations.Migration):
    dependencies = [
        ("mytask", "0006_alter_task_creator_alter_task_handler_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="task",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reviewer",
            name="user",
        ),
        migrations.AddField(
            model_name="assignment",
            name="task_id",
            field=models.CharField(
                db_index=True,
                default=mytask.models.generate_unique_task_id,
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="reviewer",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
