# Generated by Django 4.1 on 2024-09-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mytask", "0007_remove_assignment_task_remove_assignment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="target_user",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
