# Generated by Django 4.1 on 2024-10-02 07:36

from django.db import migrations, models
import mytask.models


class Migration(migrations.Migration):
    dependencies = [
        ("mytask", "0009_task_backup_field1_task_backup_field2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task_id",
            field=models.CharField(
                default=mytask.models.generate_unique_task_id, max_length=10
            ),
        ),
    ]
